CREATE SEQUENCE IF NOT EXISTS DDL_SCRIPT_ID_SEQ
  START WITH 1000;

CREATE TABLE IF NOT EXISTS ddlscript (
  id          INT NOT NULL DEFAULT NEXTVAL('DDL_SCRIPT_ID_SEQ') PRIMARY KEY,
  filename     VARCHAR(200),
  executed  timestamp
);